name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip uninstall -y numpy pandas  # Force remove existing versions
          pip install --no-cache-dir numpy==1.26.0
          pip install --no-cache-dir pandas==2.1.0
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          pytest --cov=calculator --cov-report=term-missing  # Run tests with coverage

      - name: Run pylint
        run: pylint calculator
